export interface Job {
  id: string;
  title: string;
  employer: string;
  country: string;
  location: string;
  category: string;
  type: "Full-time" | "Part-time" | "Seasonal" | "Contract";
  salary: string;
  salaryMin: number;
  sponsored: boolean;
  description: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
  accommodation: boolean;
  transport: boolean;
  meals: boolean;
  deadline: string;
  status: "open" | "closed";
  postedDate: string;
}

export const COUNTRIES = ["Canada", "United Kingdom", "Australia", "New Zealand", "Germany", "Ireland"];
export const CATEGORIES = ["Agriculture", "Manufacturing", "Hospitality", "Healthcare", "Construction", "Logistics", "IT & Technology", "Food Processing"];
export const JOB_TYPES = ["Full-time", "Part-time", "Seasonal", "Contract"] as const;

export const jobs: Job[] = [
  {
    id: "farm-worker-canada-01",
    title: "Farm Worker — Fruit Picking",
    employer: "Prairie Harvest Farms Ltd.",
    country: "Canada",
    location: "British Columbia, Canada",
    category: "Agriculture",
    type: "Seasonal",
    salary: "CAD $16–$20/hr",
    salaryMin: 16,
    sponsored: true,
    description: "Join our team for the harvest season picking apples, berries, and stone fruit across our 200-acre farm in the Okanagan Valley. Housing provided on-site.",
    responsibilities: ["Pick and sort fruit according to quality standards", "Operate basic farm equipment", "Pack produce for distribution", "Maintain cleanliness of work areas"],
    requirements: ["Physically fit and able to work outdoors", "No formal qualifications required", "Willingness to work early mornings and weekends", "Basic English communication"],
    benefits: ["Visa sponsorship through LMIA", "On-site accommodation included", "Weekly pay", "Overtime available"],
    accommodation: true, transport: false, meals: false,
    deadline: "2026-06-30",
    status: "open",
    postedDate: "2026-03-15",
  },
  {
    id: "warehouse-operative-uk-01",
    title: "Warehouse Operative",
    employer: "Summit Logistics UK",
    country: "United Kingdom",
    location: "Manchester, United Kingdom",
    category: "Logistics",
    type: "Full-time",
    salary: "£11–£14/hr",
    salaryMin: 11,
    sponsored: true,
    description: "We are looking for reliable warehouse operatives to join our distribution centre in Manchester. Role involves picking, packing, and dispatching orders.",
    responsibilities: ["Pick and pack orders accurately", "Load and unload delivery vehicles", "Maintain stock records", "Follow health and safety procedures"],
    requirements: ["Right to work or sponsored visa", "Able to lift up to 25kg", "Flexible shift availability", "Previous warehouse experience preferred"],
    benefits: ["Skilled Worker Visa sponsorship", "Pension scheme", "28 days annual leave", "Career progression opportunities"],
    accommodation: false, transport: true, meals: false,
    deadline: "2026-07-15",
    status: "open",
    postedDate: "2026-03-20",
  },
  {
    id: "meat-processing-canada-01",
    title: "Meat Processing Worker",
    employer: "Northern Protein Inc.",
    country: "Canada",
    location: "Alberta, Canada",
    category: "Food Processing",
    type: "Full-time",
    salary: "CAD $17–$22/hr",
    salaryMin: 17,
    sponsored: true,
    description: "Full-time meat processing positions available at our modern facility in Brooks, Alberta. Training provided. Accommodation assistance available.",
    responsibilities: ["Operate processing line machinery", "Quality inspection of products", "Maintain hygiene and safety standards", "Package finished products"],
    requirements: ["No experience required — full training provided", "Physically able to stand for long periods", "Comfortable working in cold environments", "Basic English"],
    benefits: ["LMIA-backed work permit", "Accommodation assistance", "Health benefits after 3 months", "Permanent residency pathway"],
    accommodation: true, transport: true, meals: true,
    deadline: "2026-08-01",
    status: "open",
    postedDate: "2026-03-25",
  },
  {
    id: "hospitality-australia-01",
    title: "Hotel Hospitality Staff",
    employer: "Coral Bay Resorts",
    country: "Australia",
    location: "Queensland, Australia",
    category: "Hospitality",
    type: "Full-time",
    salary: "AUD $25–$30/hr",
    salaryMin: 25,
    sponsored: true,
    description: "Join a world-class resort team in Queensland. Roles include front desk, food & beverage, and housekeeping. Stunning coastal location with staff accommodation.",
    responsibilities: ["Deliver exceptional guest service", "Manage check-in and check-out procedures", "Coordinate with housekeeping and F&B teams", "Handle guest inquiries professionally"],
    requirements: ["Hospitality diploma or equivalent experience", "Excellent English communication", "Customer-focused attitude", "Flexible to work weekends and holidays"],
    benefits: ["Employer-sponsored visa (subclass 482)", "Staff accommodation at discounted rate", "Meals during shifts", "Tips and service charge"],
    accommodation: true, transport: false, meals: true,
    deadline: "2026-07-20",
    status: "open",
    postedDate: "2026-04-01",
  },
  {
    id: "construction-labourer-canada-01",
    title: "Construction Labourer",
    employer: "Maple Build Corp.",
    country: "Canada",
    location: "Ontario, Canada",
    category: "Construction",
    type: "Full-time",
    salary: "CAD $18–$24/hr",
    salaryMin: 18,
    sponsored: true,
    description: "Experienced and entry-level construction labourers needed for residential and commercial projects across the Greater Toronto Area.",
    responsibilities: ["Assist with framing, concrete, and finishing work", "Operate hand and power tools", "Maintain safe and clean job sites", "Follow project manager instructions"],
    requirements: ["Physical fitness and stamina", "Construction experience preferred but not required", "Ability to work at heights", "Valid driver's licence an asset"],
    benefits: ["LMIA work permit sponsorship", "Competitive overtime rates", "Safety gear provided", "Pathway to permanent residency"],
    accommodation: false, transport: false, meals: false,
    deadline: "2026-09-01",
    status: "open",
    postedDate: "2026-04-05",
  },
  {
    id: "healthcare-assistant-uk-01",
    title: "Healthcare Assistant",
    employer: "Brightcare NHS Trust",
    country: "United Kingdom",
    location: "Birmingham, United Kingdom",
    category: "Healthcare",
    type: "Full-time",
    salary: "£10.50–£13/hr",
    salaryMin: 10,
    sponsored: true,
    description: "NHS Trust seeking compassionate healthcare assistants to support patients in hospital and community settings. Full induction and training provided.",
    responsibilities: ["Assist patients with daily living activities", "Take and record vital signs", "Support nursing staff with clinical tasks", "Maintain patient dignity and comfort"],
    requirements: ["Care Certificate or willingness to obtain", "Compassionate and patient-focused", "Good English communication skills", "DBS check required"],
    benefits: ["Health & Care Worker Visa sponsorship", "NHS pension scheme", "27 days annual leave + bank holidays", "Free uniform and training"],
    accommodation: false, transport: false, meals: false,
    deadline: "2026-08-15",
    status: "open",
    postedDate: "2026-04-02",
  },
  {
    id: "dairy-farm-nz-01",
    title: "Dairy Farm Assistant",
    employer: "Greenfield Dairy NZ",
    country: "New Zealand",
    location: "Waikato, New Zealand",
    category: "Agriculture",
    type: "Full-time",
    salary: "NZD $22–$27/hr",
    salaryMin: 22,
    sponsored: true,
    description: "Work on a modern dairy farm in New Zealand's Waikato region. Experience rural New Zealand living with on-farm accommodation included.",
    responsibilities: ["Milking operations (rotary shed)", "Pasture management and fencing", "Animal health monitoring", "Farm maintenance and equipment care"],
    requirements: ["Interest in agriculture/farming", "Physically fit for outdoor work", "Willing to start early mornings", "Driver's licence preferred"],
    benefits: ["Accredited Employer Work Visa", "On-farm housing included", "Training and upskilling provided", "Beautiful rural lifestyle"],
    accommodation: true, transport: false, meals: false,
    deadline: "2026-07-01",
    status: "open",
    postedDate: "2026-03-28",
  },
  {
    id: "it-support-germany-01",
    title: "IT Support Specialist",
    employer: "TechHaus GmbH",
    country: "Germany",
    location: "Berlin, Germany",
    category: "IT & Technology",
    type: "Full-time",
    salary: "€3,200–€4,000/mo",
    salaryMin: 3200,
    sponsored: true,
    description: "Join our growing tech company in Berlin providing first and second-line IT support. International team, English-speaking office.",
    responsibilities: ["Resolve IT support tickets", "Manage user accounts and permissions", "Maintain hardware and software inventory", "Support onboarding of new employees"],
    requirements: ["IT diploma or relevant certification", "2+ years IT support experience", "Fluent English (German a plus)", "Knowledge of Windows, macOS, and Linux"],
    benefits: ["EU Blue Card sponsorship", "30 days annual leave", "Public transport pass", "Modern office with free snacks"],
    accommodation: false, transport: true, meals: false,
    deadline: "2026-08-30",
    status: "open",
    postedDate: "2026-04-10",
  },
  {
    id: "kitchen-porter-ireland-01",
    title: "Kitchen Porter / Commis Chef",
    employer: "Atlantic Hotel Group",
    country: "Ireland",
    location: "Dublin, Ireland",
    category: "Hospitality",
    type: "Full-time",
    salary: "€12.50–€15/hr",
    salaryMin: 12,
    sponsored: true,
    description: "Busy hotel kitchen in Dublin city centre seeking kitchen porters and commis chefs. Fast-paced environment with career growth.",
    responsibilities: ["Prepare ingredients and mise en place", "Maintain kitchen cleanliness", "Assist head chef during service", "Stock management and rotation"],
    requirements: ["Kitchen experience preferred", "Food hygiene awareness", "Ability to work under pressure", "Team player"],
    benefits: ["General Employment Permit sponsorship", "Staff meals on shift", "Uniform provided", "Career progression to chef roles"],
    accommodation: false, transport: false, meals: true,
    deadline: "2026-07-31",
    status: "open",
    postedDate: "2026-04-08",
  },
];
