export interface StudyProgram {
  id: string;
  title: string;
  institution: string;
  country: string;
  city: string;
  level: "Diploma" | "Certificate" | "Undergraduate" | "Postgraduate" | "PhD";
  field: string;
  duration: string;
  tuitionRange: string;
  tuitionMin: number;
  intake: string[];
  language: string;
  scholarshipAvailable: boolean;
  workPermit: boolean;
  description: string;
  requirements: string[];
  highlights: string[];
}

export const STUDY_COUNTRIES = ["Canada", "United Kingdom", "Australia", "Germany", "Ireland", "New Zealand"];
export const STUDY_LEVELS = ["Diploma", "Certificate", "Undergraduate", "Postgraduate", "PhD"] as const;
export const STUDY_FIELDS = [
  "Business & Management",
  "Engineering & Technology",
  "Health Sciences",
  "Hospitality & Tourism",
  "Information Technology",
  "Arts & Humanities",
  "Agriculture & Environment",
  "Trades & Vocational",
];

export const studyPrograms: StudyProgram[] = [
  {
    id: "business-diploma-ca",
    title: "Diploma in Business Administration",
    institution: "Seneca Polytechnic",
    country: "Canada",
    city: "Toronto, Ontario",
    level: "Diploma",
    field: "Business & Management",
    duration: "2 years",
    tuitionRange: "CAD $15,000–$18,000/yr",
    tuitionMin: 15000,
    intake: ["September", "January"],
    language: "English",
    scholarshipAvailable: true,
    workPermit: true,
    description: "A comprehensive business diploma covering marketing, finance, management, and entrepreneurship. Includes a co-op work term for hands-on industry experience in one of Canada's top business cities.",
    requirements: ["High school diploma or equivalent", "IELTS 6.0 or equivalent", "Minimum 60% in previous studies", "Statement of purpose"],
    highlights: ["Co-op work placement included", "Post-Graduation Work Permit eligible", "Pathway to bachelor's degree", "Downtown Toronto campus"],
  },
  {
    id: "nursing-uk",
    title: "BSc Nursing (Adult)",
    institution: "University of Birmingham",
    country: "United Kingdom",
    city: "Birmingham",
    level: "Undergraduate",
    field: "Health Sciences",
    duration: "3 years",
    tuitionRange: "£20,000–£24,000/yr",
    tuitionMin: 20000,
    intake: ["September"],
    language: "English",
    scholarshipAvailable: true,
    workPermit: true,
    description: "A professional nursing degree leading to NMC registration. Combines academic study with extensive clinical placements in NHS hospitals and community settings across the West Midlands.",
    requirements: ["IELTS 7.0 (min 6.5 each)", "A-levels or equivalent", "Health and DBS clearance", "Interview required"],
    highlights: ["Direct pathway to NHS employment", "Graduate Visa (2 years post-study work)", "50% clinical placement", "Scholarship opportunities for international students"],
  },
  {
    id: "it-postgrad-au",
    title: "Master of Information Technology",
    institution: "University of Melbourne",
    country: "Australia",
    city: "Melbourne, Victoria",
    level: "Postgraduate",
    field: "Information Technology",
    duration: "2 years",
    tuitionRange: "AUD $44,000–$48,000/yr",
    tuitionMin: 44000,
    intake: ["February", "July"],
    language: "English",
    scholarshipAvailable: true,
    workPermit: true,
    description: "A world-ranked IT program covering AI, cybersecurity, data science, and software engineering. Ideal for career changers and IT professionals seeking advanced skills.",
    requirements: ["Bachelor's degree in any field", "IELTS 6.5 (min 6.0 each)", "Minimum GPA 3.0/4.0", "Two academic references"],
    highlights: ["QS Top 50 ranked university", "Post-Study Work Visa (2–4 years)", "Industry capstone project", "Access to Melbourne's tech ecosystem"],
  },
  {
    id: "hospitality-diploma-nz",
    title: "Diploma in Hospitality Management",
    institution: "Auckland University of Technology",
    country: "New Zealand",
    city: "Auckland",
    level: "Diploma",
    field: "Hospitality & Tourism",
    duration: "18 months",
    tuitionRange: "NZD $22,000–$25,000/yr",
    tuitionMin: 22000,
    intake: ["February", "July"],
    language: "English",
    scholarshipAvailable: false,
    workPermit: true,
    description: "Practical hospitality management training including food & beverage operations, hotel management, and event planning. Strong industry connections in New Zealand's tourism sector.",
    requirements: ["High school diploma", "IELTS 5.5 or equivalent", "No prior experience required", "Genuine student declaration"],
    highlights: ["Post-Study Work Visa eligible", "Industry work placement", "Auckland's hospitality sector access", "Pathway to degree"],
  },
  {
    id: "engineering-de",
    title: "MSc Mechanical Engineering",
    institution: "Technical University of Munich",
    country: "Germany",
    city: "Munich, Bavaria",
    level: "Postgraduate",
    field: "Engineering & Technology",
    duration: "2 years",
    tuitionRange: "€300–€500/semester (public)",
    tuitionMin: 300,
    intake: ["October", "April"],
    language: "English",
    scholarshipAvailable: true,
    workPermit: true,
    description: "A prestigious engineering master's at one of Europe's top technical universities. Low tuition at a public university with world-class research facilities and strong ties to German automotive and manufacturing industries.",
    requirements: ["Bachelor's in Engineering (min 2.5 GPA)", "IELTS 6.5 or TOEFL 88", "GRE recommended", "Motivation letter"],
    highlights: ["Near-free tuition (public university)", "18-month post-study job search visa", "Industry partnerships with BMW, Siemens", "English-taught program"],
  },
  {
    id: "agriculture-ca",
    title: "Certificate in Agriculture Technology",
    institution: "Olds College",
    country: "Canada",
    city: "Olds, Alberta",
    level: "Certificate",
    field: "Agriculture & Environment",
    duration: "1 year",
    tuitionRange: "CAD $12,000–$14,000/yr",
    tuitionMin: 12000,
    intake: ["September"],
    language: "English",
    scholarshipAvailable: false,
    workPermit: true,
    description: "Hands-on agricultural technology training covering precision farming, crop science, livestock management, and sustainable agriculture practices on a working farm campus.",
    requirements: ["High school diploma", "IELTS 5.5 or equivalent", "Interest in agriculture", "Basic math and science"],
    highlights: ["On-campus farm experience", "PGWP eligible", "Small class sizes", "Rural Alberta lifestyle"],
  },
  {
    id: "business-postgrad-ie",
    title: "MSc International Business",
    institution: "Trinity College Dublin",
    country: "Ireland",
    city: "Dublin",
    level: "Postgraduate",
    field: "Business & Management",
    duration: "1 year",
    tuitionRange: "€18,000–€22,000",
    tuitionMin: 18000,
    intake: ["September"],
    language: "English",
    scholarshipAvailable: true,
    workPermit: true,
    description: "A one-year intensive master's in international business at Ireland's top university. Covers global strategy, cross-cultural management, and international finance with a strong emphasis on employability.",
    requirements: ["Bachelor's degree (2.1 or equivalent)", "IELTS 6.5 (min 6.0 each)", "Professional experience preferred", "Two references"],
    highlights: ["1-year Stay Back Visa for master's", "Trinity ranked #81 globally", "Access to EU multinational HQs", "Dublin's tech & finance hub"],
  },
  {
    id: "trades-plumbing-au",
    title: "Certificate III in Plumbing",
    institution: "TAFE NSW",
    country: "Australia",
    city: "Sydney, NSW",
    level: "Certificate",
    field: "Trades & Vocational",
    duration: "2 years",
    tuitionRange: "AUD $18,000–$22,000/yr",
    tuitionMin: 18000,
    intake: ["February", "July"],
    language: "English",
    scholarshipAvailable: false,
    workPermit: true,
    description: "Practical trade qualification in plumbing covering residential and commercial installations. Combines classroom theory with supervised on-site training placements across Sydney.",
    requirements: ["Year 10 completion or equivalent", "IELTS 5.5", "Physical fitness", "Working With Children Check"],
    highlights: ["Skilled occupation list (migration pathway)", "Post-Study Work Visa eligible", "High demand trade in Australia", "Hands-on workshop training"],
  },
  {
    id: "arts-humanities-uk",
    title: "BA Creative Arts & Media",
    institution: "University of the Arts London",
    country: "United Kingdom",
    city: "London",
    level: "Undergraduate",
    field: "Arts & Humanities",
    duration: "3 years",
    tuitionRange: "£22,000–£26,000/yr",
    tuitionMin: 22000,
    intake: ["September"],
    language: "English",
    scholarshipAvailable: true,
    workPermit: true,
    description: "Study at one of the world's top creative institutions in the heart of London. Covers digital media, graphic design, film production, and creative writing with industry-standard facilities.",
    requirements: ["Foundation diploma or A-levels", "IELTS 6.0", "Creative portfolio required", "Personal statement"],
    highlights: ["World-renowned creative institution", "Graduate Visa (2 years post-study)", "London creative industry access", "Portfolio-based admission"],
  },
];
