/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as StudyProgramIdRouteImport } from './routes/study/$programId'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as ApplyWorkVisaRouteImport } from './routes/apply/work-visa'
import { Route as ApplyStudyRouteImport } from './routes/apply/study'
import { Route as AgentsSettingsRouteImport } from './routes/agents/settings'
import { Route as AgentsRegisterRouteImport } from './routes/agents/register'
import { Route as AgentsPaymentsRouteImport } from './routes/agents/payments'
import { Route as AgentsMessagesRouteImport } from './routes/agents/messages'
import { Route as AgentsLoginRouteImport } from './routes/agents/login'
import { Route as AgentsDashboardRouteImport } from './routes/agents/dashboard'
import { Route as AgentsClientsIndexRouteImport } from './routes/agents/clients/index'
import { Route as AgentsApplicationsIndexRouteImport } from './routes/agents/applications/index'
import { Route as AgentsClientsNewRouteImport } from './routes/agents/clients/new'
import { Route as AgentsApplicationsWorkVisaRouteImport } from './routes/agents/applications/work-visa'
import { Route as AgentsApplicationsStudyVisaRouteImport } from './routes/agents/applications/study-visa'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyProgramIdRoute = StudyProgramIdRouteImport.update({
  id: '/study/$programId',
  path: '/study/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyWorkVisaRoute = ApplyWorkVisaRouteImport.update({
  id: '/apply/work-visa',
  path: '/apply/work-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyStudyRoute = ApplyStudyRouteImport.update({
  id: '/apply/study',
  path: '/apply/study',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSettingsRoute = AgentsSettingsRouteImport.update({
  id: '/agents/settings',
  path: '/agents/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRegisterRoute = AgentsRegisterRouteImport.update({
  id: '/agents/register',
  path: '/agents/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsPaymentsRoute = AgentsPaymentsRouteImport.update({
  id: '/agents/payments',
  path: '/agents/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsMessagesRoute = AgentsMessagesRouteImport.update({
  id: '/agents/messages',
  path: '/agents/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsLoginRoute = AgentsLoginRouteImport.update({
  id: '/agents/login',
  path: '/agents/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDashboardRoute = AgentsDashboardRouteImport.update({
  id: '/agents/dashboard',
  path: '/agents/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsClientsIndexRoute = AgentsClientsIndexRouteImport.update({
  id: '/agents/clients/',
  path: '/agents/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsApplicationsIndexRoute = AgentsApplicationsIndexRouteImport.update({
  id: '/agents/applications/',
  path: '/agents/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsClientsNewRoute = AgentsClientsNewRouteImport.update({
  id: '/agents/clients/new',
  path: '/agents/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsApplicationsWorkVisaRoute =
  AgentsApplicationsWorkVisaRouteImport.update({
    id: '/agents/applications/work-visa',
    path: '/agents/applications/work-visa',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsApplicationsStudyVisaRoute =
  AgentsApplicationsStudyVisaRouteImport.update({
    id: '/agents/applications/study-visa',
    path: '/agents/applications/study-visa',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/login': typeof AgentsLoginRoute
  '/agents/messages': typeof AgentsMessagesRoute
  '/agents/payments': typeof AgentsPaymentsRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/agents/settings': typeof AgentsSettingsRoute
  '/apply/study': typeof ApplyStudyRoute
  '/apply/work-visa': typeof ApplyWorkVisaRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/study/$programId': typeof StudyProgramIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/agents/applications/study-visa': typeof AgentsApplicationsStudyVisaRoute
  '/agents/applications/work-visa': typeof AgentsApplicationsWorkVisaRoute
  '/agents/clients/new': typeof AgentsClientsNewRoute
  '/agents/applications/': typeof AgentsApplicationsIndexRoute
  '/agents/clients/': typeof AgentsClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/login': typeof AgentsLoginRoute
  '/agents/messages': typeof AgentsMessagesRoute
  '/agents/payments': typeof AgentsPaymentsRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/agents/settings': typeof AgentsSettingsRoute
  '/apply/study': typeof ApplyStudyRoute
  '/apply/work-visa': typeof ApplyWorkVisaRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/study/$programId': typeof StudyProgramIdRoute
  '/jobs': typeof JobsIndexRoute
  '/study': typeof StudyIndexRoute
  '/agents/applications/study-visa': typeof AgentsApplicationsStudyVisaRoute
  '/agents/applications/work-visa': typeof AgentsApplicationsWorkVisaRoute
  '/agents/clients/new': typeof AgentsClientsNewRoute
  '/agents/applications': typeof AgentsApplicationsIndexRoute
  '/agents/clients': typeof AgentsClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/login': typeof AgentsLoginRoute
  '/agents/messages': typeof AgentsMessagesRoute
  '/agents/payments': typeof AgentsPaymentsRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/agents/settings': typeof AgentsSettingsRoute
  '/apply/study': typeof ApplyStudyRoute
  '/apply/work-visa': typeof ApplyWorkVisaRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/study/$programId': typeof StudyProgramIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/study/': typeof StudyIndexRoute
  '/agents/applications/study-visa': typeof AgentsApplicationsStudyVisaRoute
  '/agents/applications/work-visa': typeof AgentsApplicationsWorkVisaRoute
  '/agents/clients/new': typeof AgentsClientsNewRoute
  '/agents/applications/': typeof AgentsApplicationsIndexRoute
  '/agents/clients/': typeof AgentsClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/agents/dashboard'
    | '/agents/login'
    | '/agents/messages'
    | '/agents/payments'
    | '/agents/register'
    | '/agents/settings'
    | '/apply/study'
    | '/apply/work-visa'
    | '/jobs/$jobId'
    | '/study/$programId'
    | '/jobs/'
    | '/study/'
    | '/agents/applications/study-visa'
    | '/agents/applications/work-visa'
    | '/agents/clients/new'
    | '/agents/applications/'
    | '/agents/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/agents/dashboard'
    | '/agents/login'
    | '/agents/messages'
    | '/agents/payments'
    | '/agents/register'
    | '/agents/settings'
    | '/apply/study'
    | '/apply/work-visa'
    | '/jobs/$jobId'
    | '/study/$programId'
    | '/jobs'
    | '/study'
    | '/agents/applications/study-visa'
    | '/agents/applications/work-visa'
    | '/agents/clients/new'
    | '/agents/applications'
    | '/agents/clients'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/agents/dashboard'
    | '/agents/login'
    | '/agents/messages'
    | '/agents/payments'
    | '/agents/register'
    | '/agents/settings'
    | '/apply/study'
    | '/apply/work-visa'
    | '/jobs/$jobId'
    | '/study/$programId'
    | '/jobs/'
    | '/study/'
    | '/agents/applications/study-visa'
    | '/agents/applications/work-visa'
    | '/agents/clients/new'
    | '/agents/applications/'
    | '/agents/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AgentsDashboardRoute: typeof AgentsDashboardRoute
  AgentsLoginRoute: typeof AgentsLoginRoute
  AgentsMessagesRoute: typeof AgentsMessagesRoute
  AgentsPaymentsRoute: typeof AgentsPaymentsRoute
  AgentsRegisterRoute: typeof AgentsRegisterRoute
  AgentsSettingsRoute: typeof AgentsSettingsRoute
  ApplyStudyRoute: typeof ApplyStudyRoute
  ApplyWorkVisaRoute: typeof ApplyWorkVisaRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  StudyProgramIdRoute: typeof StudyProgramIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  AgentsApplicationsStudyVisaRoute: typeof AgentsApplicationsStudyVisaRoute
  AgentsApplicationsWorkVisaRoute: typeof AgentsApplicationsWorkVisaRoute
  AgentsClientsNewRoute: typeof AgentsClientsNewRoute
  AgentsApplicationsIndexRoute: typeof AgentsApplicationsIndexRoute
  AgentsClientsIndexRoute: typeof AgentsClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$programId': {
      id: '/study/$programId'
      path: '/study/$programId'
      fullPath: '/study/$programId'
      preLoaderRoute: typeof StudyProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/work-visa': {
      id: '/apply/work-visa'
      path: '/apply/work-visa'
      fullPath: '/apply/work-visa'
      preLoaderRoute: typeof ApplyWorkVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/study': {
      id: '/apply/study'
      path: '/apply/study'
      fullPath: '/apply/study'
      preLoaderRoute: typeof ApplyStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/settings': {
      id: '/agents/settings'
      path: '/agents/settings'
      fullPath: '/agents/settings'
      preLoaderRoute: typeof AgentsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/register': {
      id: '/agents/register'
      path: '/agents/register'
      fullPath: '/agents/register'
      preLoaderRoute: typeof AgentsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/payments': {
      id: '/agents/payments'
      path: '/agents/payments'
      fullPath: '/agents/payments'
      preLoaderRoute: typeof AgentsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/messages': {
      id: '/agents/messages'
      path: '/agents/messages'
      fullPath: '/agents/messages'
      preLoaderRoute: typeof AgentsMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/login': {
      id: '/agents/login'
      path: '/agents/login'
      fullPath: '/agents/login'
      preLoaderRoute: typeof AgentsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/dashboard': {
      id: '/agents/dashboard'
      path: '/agents/dashboard'
      fullPath: '/agents/dashboard'
      preLoaderRoute: typeof AgentsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/clients/': {
      id: '/agents/clients/'
      path: '/agents/clients'
      fullPath: '/agents/clients/'
      preLoaderRoute: typeof AgentsClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/applications/': {
      id: '/agents/applications/'
      path: '/agents/applications'
      fullPath: '/agents/applications/'
      preLoaderRoute: typeof AgentsApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/clients/new': {
      id: '/agents/clients/new'
      path: '/agents/clients/new'
      fullPath: '/agents/clients/new'
      preLoaderRoute: typeof AgentsClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/applications/work-visa': {
      id: '/agents/applications/work-visa'
      path: '/agents/applications/work-visa'
      fullPath: '/agents/applications/work-visa'
      preLoaderRoute: typeof AgentsApplicationsWorkVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/applications/study-visa': {
      id: '/agents/applications/study-visa'
      path: '/agents/applications/study-visa'
      fullPath: '/agents/applications/study-visa'
      preLoaderRoute: typeof AgentsApplicationsStudyVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AgentsDashboardRoute: AgentsDashboardRoute,
  AgentsLoginRoute: AgentsLoginRoute,
  AgentsMessagesRoute: AgentsMessagesRoute,
  AgentsPaymentsRoute: AgentsPaymentsRoute,
  AgentsRegisterRoute: AgentsRegisterRoute,
  AgentsSettingsRoute: AgentsSettingsRoute,
  ApplyStudyRoute: ApplyStudyRoute,
  ApplyWorkVisaRoute: ApplyWorkVisaRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  StudyProgramIdRoute: StudyProgramIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  AgentsApplicationsStudyVisaRoute: AgentsApplicationsStudyVisaRoute,
  AgentsApplicationsWorkVisaRoute: AgentsApplicationsWorkVisaRoute,
  AgentsClientsNewRoute: AgentsClientsNewRoute,
  AgentsApplicationsIndexRoute: AgentsApplicationsIndexRoute,
  AgentsClientsIndexRoute: AgentsClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
